//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamingZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamRequest
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int NoOfPlayers { get; set; }
        public Nullable<int> TeamRating { get; set; }
        public string Description { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> isApproved { get; set; }
    }
}
